
## Explore Monefy to discover useful information about better way to track my expenses

### 180 min

#### Risks

* It might not be clear how to get started
* Short time to test large number of features  
* There is a bug that stops me doing what I think I should be able to do

#### Questions
* How does a user add an expense?
* How easy it is to get started?

#### Setup

* Install the app to my IOS device [https://monefy.me]

#### Comments

* There are no simple instructions how to get started when I open the app

### Test Charters
* Explore new expenses with adding various types of expenses to discover if reported correctly **20 Min**
* Explore new income with adding various types of incomes to discover if reported correctly **20 Min**
* Explore balance with reporting various incomes/expenses to discover if reports are currently calculated **20 Min**
* Explore managing categories with fiddling with adding removing them to discover if it can be done easily **20 Min**
* Explore languages with different languages to discover if localisation is working  **10 Min**
* Explore currencies with different currencies to discover currency conversion is working **10 Min**
* Explore data backup with all offered options to discover if app data is managed easily  **10 Min**
* Explore Accounts with adding/removing accounts to discover how changes are reflected in user profile **10 Min**
* Explore Export to file with checking file content on Excel to discover if data is stored correctly on app **10 Min**

## Findings
* Important test scenarios worked as expected. App's happy path and main features are working as expected. 
  User can report his incomes and expense. Correct indication about his budget will be given. Data generated by 
  the app can be backed up and restored safely.
  

* It was difficult to get started right away. The UI icons aren't clear about their functionality. 
  I had to do some tries to get the hang of it.
  

* Using more advance features like Date Filtering and New Transfer were difficult to understand.
  

* 3 bugs were discovered during testing. Non of them is critical, since they are not part of the happy path, and the
  scenarios to reproduce aren't something a daily user should come across.
  
#### Bugs
1. Deleting the cash and visa accounts will crash the app, no way to recover than reinstall the app.
2. Changing currency doesn't convert reported records value from previous to new currency.
3. If I removed all Income types from Categories I can no longer report incomes if I don't have a pro version. 

## Risk Mitigation
* It might not be clear how to get started: I read about the main features of the app on https://monefy.me/  
  

* Short time to test large number of features: app includes many features. I focused on testing happy path and 
  features that include handling data first to establish the stability of the app.
  

* There is a bug that stops me doing what I think I should be able to do: There are no requirements. I used the 
  highlight on https://monefy.me/ as expected result of main features.




